### ISSUE TITLE
burpui.cfg gets overwritten

### ISSUE THREAD

**Issue by cgsecret** [pschiffe/docker-burp#5]
hi,

i wanna do changes to the burpui.cfg to activate ldap. neither editing the file while running the containers or while they are stopped worked for me. As soon as i restart the container the config is resetted. 

Here is my docker-compose.yml:
```
version: '3'

services:
  burp-server:
    container_name: burp
    image: pschiffe/burp-server
    tty: true
    volumes:
      - burp-server-conf:/etc/burp
      - burp-server-data:/var/spool/burp
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    environment:
      - BUI_AGENT_PASSWORD=secret-burp-server-pw
      - "BURP_CLIENTS_CONFIG=burp-client:super-secret"
#    networks:
#      burp:
#        aliases:
#          - burp

  burp-ui:
    image: pschiffe/burp-ui
    container_name: burp-ui
    volumes:
      - burp-ui-conf:/etc/burp
    environment:
      - BUI_AGENT_PASSWORD=secret-burp-server-pw
 #   networks:
 #     - burp
 #     - default
    ports:
      - "8020:5000"
    depends_on:
      - burp-server
    labels:     
      - "traefik.enable=true"   
      - "traefik.http.services.burpui.loadbalancer.server.port=5000"
      - "traefik.http.routers.burpui.entrypoints=web"   
      - "traefik.http.routers.burpui.rule=Host(`burp.local`)"


#networks:
#  burp:

volumes:
  burp-server-conf:
  burp-server-data:
  burp-ui-conf:
```
